version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database  # Example dependency on a database service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:5000  # Example environment variable for backend URL
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  database:
    image: mongo:latest  # Example MongoDB service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
 
